python3 canberraDistance_executer.py -i '/Users/alduck/Documents/Github/SelectingConstrainingMRsScSoft/Step_1_TD-Generation/Group_02/td_ttd_G02.json' -o canberraDistance_logs
python3 chebyshevDistance_executer.py -i '/Users/alduck/Documents/Github/SelectingConstrainingMRsScSoft/Step_1_TD-Generation/Group_02/td_ttd_G02.json' -o chebyshevDistance_logs
python3 chiSquare_executer.py -i '/Users/alduck/Documents/Github/SelectingConstrainingMRsScSoft/Step_1_TD-Generation/Group_02/td_ttd_G02.json' -o chiSquare_logs
python3 consineDistance_executer.py -i '/Users/alduck/Documents/Github/SelectingConstrainingMRsScSoft/Step_1_TD-Generation/Group_02/td_ttd_G02.json' -o consineDistance_logs
python3 covariance_executer.py -i '/Users/alduck/Documents/Github/SelectingConstrainingMRsScSoft/Step_1_TD-Generation/Group_02/td_ttd_G02.json' -o covariance_logs
python3 distance1_executer.py -i '/Users/alduck/Documents/Github/SelectingConstrainingMRsScSoft/Step_1_TD-Generation/Group_02/td_ttd_G02.json' -o distance1_logs
python3 distanceInf_executer.py -i '/Users/alduck/Documents/Github/SelectingConstrainingMRsScSoft/Step_1_TD-Generation/Group_02/td_ttd_G02.json' -o distanceInf_logs
python3 dotProduct_executer.py -i '/Users/alduck/Documents/Github/SelectingConstrainingMRsScSoft/Step_1_TD-Generation/Group_02/td_ttd_G02.json' -o dotProduct_logs
python3 errorRate_executer.py -i '/Users/alduck/Documents/Github/SelectingConstrainingMRsScSoft/Step_1_TD-Generation/Group_02/td_ttd_G02.json' -o errorRate_logs
python3 find_euc_dist_executer.py -i '/Users/alduck/Documents/Github/SelectingConstrainingMRsScSoft/Step_1_TD-Generation/Group_02/td_ttd_G02.json' -o find_euc_dist_logs
python3 g_executer.py -i '/Users/alduck/Documents/Github/SelectingConstrainingMRsScSoft/Step_1_TD-Generation/Group_02/td_ttd_G02.json' -o g_logs
python3 hamming_dist_executer.py -i '/Users/alduck/Documents/Github/SelectingConstrainingMRsScSoft/Step_1_TD-Generation/Group_02/td_ttd_G02.json' -o hamming_dist_logs
python3 manhattanDistance_executer.py -i '/Users/alduck/Documents/Github/SelectingConstrainingMRsScSoft/Step_1_TD-Generation/Group_02/td_ttd_G02.json' -o manhattanDistance_logs
python3 manhattanDistance2_executer.py -i '/Users/alduck/Documents/Github/SelectingConstrainingMRsScSoft/Step_1_TD-Generation/Group_02/td_ttd_G02.json' -o manhattanDistance2_logs
python3 meanDifference_executer.py -i '/Users/alduck/Documents/Github/SelectingConstrainingMRsScSoft/Step_1_TD-Generation/Group_02/td_ttd_G02.json' -o meanDifference_logs
python3 mean_absolute_error_executer.py -i '/Users/alduck/Documents/Github/SelectingConstrainingMRsScSoft/Step_1_TD-Generation/Group_02/td_ttd_G02.json' -o mean_absolute_error_logs
python3 polevl_executer.py -i '/Users/alduck/Documents/Github/SelectingConstrainingMRsScSoft/Step_1_TD-Generation/Group_02/td_ttd_G02.json' -o polevl_logs
python3 pooledVariance_executer.py -i '/Users/alduck/Documents/Github/SelectingConstrainingMRsScSoft/Step_1_TD-Generation/Group_02/td_ttd_G02.json' -o pooledVariance_logs
python3 sampleWeightefVariance_executer.py -i '/Users/alduck/Documents/Github/SelectingConstrainingMRsScSoft/Step_1_TD-Generation/Group_02/td_ttd_G02.json' -o sampleWeightefVariance_logs
python3 tanimotoDistance_executer.py -i '/Users/alduck/Documents/Github/SelectingConstrainingMRsScSoft/Step_1_TD-Generation/Group_02/td_ttd_G02.json' -o tanimotoDistance_logs
python3 varianceDifference_executer.py -i '/Users/alduck/Documents/Github/SelectingConstrainingMRsScSoft/Step_1_TD-Generation/Group_02/td_ttd_G02.json' -o varianceDifference_logs
python3 weightedAverage_executer.py -i '/Users/alduck/Documents/Github/SelectingConstrainingMRsScSoft/Step_1_TD-Generation/Group_02/td_ttd_G02.json' -o weightedAverage_logs
python3 weightedMean_executer.py -i '/Users/alduck/Documents/Github/SelectingConstrainingMRsScSoft/Step_1_TD-Generation/Group_02/td_ttd_G02.json' -o weightedMean_logs
python3 weightedRMS_executer.py -i '/Users/alduck/Documents/Github/SelectingConstrainingMRsScSoft/Step_1_TD-Generation/Group_02/td_ttd_G02.json' -o weightedRMS_logs